/**
 * Generated by scripts/emitRedirects.mjs from content/redirects.json.
 * DO NOT EDIT BY HAND — edit the registry, then run: node scripts/emitRedirects.mjs
 *
 * Vercel's `redirects` config only accepts 3xx status codes, so the
 * registry's 410 rules (content removed permanently: seller spam, archived
 * junk, feeds) are enforced here. Middleware runs BEFORE rewrites, so these
 * paths return a real 410 instead of the SPA shell. 301 rules stay in
 * vercel.json where they run at the edge.
 */
const GONE = [
  {
    "source": "/%D8%AD%D8%A8%D9%88%D8%A8-%D8%B3%D8%A7%D9%8A%D8%AA%D9%88%D8%AA%D9%83-%D9%84%D9%84%D8%A8%D9%8A%D8%B9.*",
    "regex": true,
    "reason": "Legacy seller-spam URL family with embedded phone numbers — gone, no educational replacement."
  },
  {
    "source": "/(?:2018|2019|2020|2021)/(.*)",
    "regex": true,
    "reason": "2018–2021 Blogger-era auto-scraped content (unrelated to the current medical platform). No replacement exists."
  },
  {
    "source": "/feed",
    "regex": false,
    "reason": "Legacy feed endpoint — gone."
  },
  {
    "source": "/feed/",
    "regex": false,
    "reason": "Legacy feed endpoint — gone."
  },
  {
    "source": "/(.*)/feed",
    "regex": true,
    "reason": "Legacy per-page feed endpoints — gone."
  },
  {
    "source": "/(.*)/feed/",
    "regex": true,
    "reason": "Legacy per-page feed endpoints — gone."
  }
];

const exactGone = new Set(GONE.filter((rule) => !rule.regex).map((rule) => rule.source));
const regexGone = GONE.filter((rule) => rule.regex).map((rule) => new RegExp("^(?:" + rule.source + ")$"));

function safeDecode(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

export default function middleware(request) {
  const pathname = new URL(request.url).pathname;
  const decoded = safeDecode(pathname);
  const gone = exactGone.has(pathname) || exactGone.has(decoded) || regexGone.some((re) => re.test(pathname) || re.test(decoded));
  if (!gone) return undefined; // pass through

  const body = "<!doctype html><html lang=\"ar\" dir=\"rtl\"><meta charset=\"utf-8\"><title>410 Gone</title><body style=\"font-family:sans-serif;text-align:center;padding:3rem 1rem\"><h1>410 Gone</h1><p>هذا المحتوى أُزيل نهائياً من الموقع.</p><p><a href=\"/\">العودة إلى الصفحة الرئيسية</a></p></body></html>";
  return new Response(body, {
    status: 410,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=3600",
    },
  });
}

export const config = {
  // Run only for content routes: exclude api, images, sitemap and robots.
  matcher: ["/((?!api/|images/|assets/|_next/|sitemap\\.xml|robots\\.txt).*)"],
};
