/**
 * emitRedirects — regenerates the deployed redirect surface from the canonical
 * registry at content/redirects.json:
 *
 *   1. vercel.json `redirects`  — 301 rules (with destination) + the
 *      www -> apex rule. Vercel's redirects config only accepts 3xx status
 *      codes (301, 302, 303, 307, 308), so ONLY 301s live here.
 *
 *   2. middleware.js            — the registry's 410 rules (content removed
 *      permanently: seller spam, archived junk, feeds). Vercel middleware runs
 *      before rewrites, so these return a real 410 instead of the SPA shell.
 *
 * Both outputs are fully generated: edit content/redirects.json, then run this
 * script (it also runs as a prebuild safety net, so the deployed rules can
 * never drift from the registry shown in the CMS Redirect Manager).
 *
 * Violations (redirect loops, non-301/410 statuses, 301 without destination)
 * abort the emit instead of writing a broken config.
 *
 * Usage: node scripts/emitRedirects.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const REGISTRY_PATH = path.join(ROOT, "content", "redirects.json");
const VERCEL_PATH = path.join(ROOT, "vercel.json");
const MIDDLEWARE_PATH = path.join(ROOT, "middleware.js");

/** Percent-encode every non-ASCII code point, preserving ASCII regex syntax. */
function encodePath(source) {
  let out = "";
  for (const ch of source) {
    if (ch.codePointAt(0) > 127) out += encodeURIComponent(ch);
    else out += ch;
  }
  return out;
}

function validate(registry) {
  const problems = [];
  const sources = new Map();
  for (const rule of registry.rules) {
    if (!rule || typeof rule.source !== "string" || !rule.source) {
      problems.push("rule without a source");
      continue;
    }
    if (![301, 410].includes(rule.statusCode)) {
      problems.push(`${rule.source}: unsupported statusCode ${rule.statusCode} (only 301/410)`);
    }
    if (rule.statusCode === 301 && !rule.destination) {
      problems.push(`${rule.source}: 301 requires a destination`);
    }
    const key = encodePath(rule.source);
    if (sources.has(key)) {
      problems.push(`${rule.source}: duplicate source`);
    }
    sources.set(key, rule);
  }
  // Loop protection: a destination must not itself be another rule's source.
  for (const rule of registry.rules) {
    if (rule.destination && sources.has(rule.destination)) {
      problems.push(`${rule.source} -> ${rule.destination}: redirect loop (destination is another source)`);
    }
  }
  return problems;
}

function renderMiddleware(registry) {
  const gone = registry.rules.filter((rule) => rule.statusCode === 410);
  const entries = gone.map((rule) => ({
    source: encodePath(rule.source),
    regex: rule.isRegex === true,
    reason: String(rule.reason ?? "").replace(/[\n\r"]/g, " "),
  }));
  return `/**
 * Generated by scripts/emitRedirects.mjs from content/redirects.json.
 * DO NOT EDIT BY HAND — edit the registry, then run: node scripts/emitRedirects.mjs
 *
 * Vercel's \`redirects\` config only accepts 3xx status codes, so the
 * registry's 410 rules (content removed permanently: seller spam, archived
 * junk, feeds) are enforced here. Middleware runs BEFORE rewrites, so these
 * paths return a real 410 instead of the SPA shell. 301 rules stay in
 * vercel.json where they run at the edge.
 */
const GONE = ${JSON.stringify(entries, null, 2)};

const exactGone = new Set(GONE.filter((rule) => !rule.regex).map((rule) => rule.source));
const regexGone = GONE.filter((rule) => rule.regex).map((rule) => new RegExp("^(?:" + rule.source + ")$"));

function safeDecode(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

export default function middleware(request) {
  const pathname = new URL(request.url).pathname;
  const decoded = safeDecode(pathname);
  const gone = exactGone.has(pathname) || exactGone.has(decoded) || regexGone.some((re) => re.test(pathname) || re.test(decoded));
  if (!gone) return undefined; // pass through

  const body = "<!doctype html><html lang=\\"ar\\" dir=\\"rtl\\"><meta charset=\\"utf-8\\"><title>410 Gone</title><body style=\\"font-family:sans-serif;text-align:center;padding:3rem 1rem\\"><h1>410 Gone</h1><p>هذا المحتوى أُزيل نهائياً من الموقع.</p><p><a href=\\"/\\">العودة إلى الصفحة الرئيسية</a></p></body></html>";
  return new Response(body, {
    status: 410,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=3600",
    },
  });
}

export const config = {
  // Run only for content routes: exclude api, images, sitemap and robots.
  matcher: ["/((?!api/|images/|assets/|_next/|sitemap\\\\.xml|robots\\\\.txt).*)"],
};
`;
}

function main() {
  const registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, "utf8"));
  const problems = validate(registry);
  if (problems.length) {
    console.error("[redirects] aborting: " + problems.join("; "));
    process.exit(1);
  }

  const current = JSON.parse(fs.readFileSync(VERCEL_PATH, "utf8"));

  // vercel.json: www -> apex + 301s only (Vercel redirects support 3xx only).
  const redirects = [];
  if (registry.wwwToApex) {
    redirects.push({
      source: "https://www.saudiersaa.com/(.*)",
      destination: "https://saudiersaa.com/$1",
      permanent: true,
    });
  }
  const goneCount = registry.rules.filter((rule) => rule.statusCode === 410).length;
  for (const rule of registry.rules) {
    if (rule.statusCode !== 301) continue;
    redirects.push({
      source: encodePath(rule.source),
      destination: rule.destination,
      statusCode: 301,
    });
  }

  const next = { ...current, redirects };
  fs.writeFileSync(VERCEL_PATH, JSON.stringify(next, null, 2) + "\n");

  fs.writeFileSync(MIDDLEWARE_PATH, renderMiddleware(registry));
  console.log(
    `[redirects] vercel.json: ${redirects.length} edge rules (301 + www->apex) · middleware.js: ${goneCount} gone rules (410)`,
  );
}

main();
