/**
 * emitStrategyMd — regenerates content-strategy-100.md from the canonical
 * 100-topic registry at content/map.json, so the human-readable strategy
 * document can never drift from the data the CMS renders.
 *
 * Usage: node scripts/emitStrategyMd.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const map = JSON.parse(fs.readFileSync(path.join(ROOT, "content", "map.json"), "utf8"));

function esc(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function row(item) {
  return [
    item.id,
    esc(item.topic),
    esc(item.primaryKeyword),
    item.secondaryKeywords.map(esc).join("، "),
    item.searchIntent,
    item.country,
    item.cityRelevance.length ? item.cityRelevance.map(esc).join("؛ ") : "—",
    item.priority,
    `\`${item.targetUrl}\``,
    `\`${item.parent}\``,
    item.related.map((r) => `\`${r}\``).join(" "),
    item.status + (item.notes ? ` (${esc(item.notes)})` : ""),
  ].join(" | ");
}

const byCluster = new Map();
for (const cluster of map.clusters) byCluster.set(cluster.id, []);
for (const item of map.items) {
  if (!byCluster.has(item.cluster)) byCluster.set(item.cluster, []);
  byCluster.get(item.cluster).push(item);
}

const statusCount = {};
for (const item of map.items) statusCount[item.status] = (statusCount[item.status] ?? 0) + 1;
const priorityCount = {};
for (const item of map.items) priorityCount[item.priority] = (priorityCount[item.priority] ?? 0) + 1;
const p0Items = map.items.filter((i) => i.priority === "P0");
const p0 = p0Items.map((i) => i.id).join(", ");
const p0Done = p0Items.filter((i) => i.status === "PUBLISHED" || i.status === "UPDATED");
const p1 = map.items.filter((i) => i.priority === "P1").length;
const p2 = map.items.filter((i) => i.priority === "P2").length;
const p3 = map.items.filter((i) => i.priority === "P3").length;

const head = `# Content Strategy — 100 Topics

Topical-authority plan for **saudiersaa.com** targeting Saudi Arabia, UAE,
Kuwait and Bahrain.

> This file is generated by \`scripts/emitStrategyMd.mjs\` from the canonical
> registry \`content/map.json\` (the same data the CMS Content Map renders).
> Edit the JSON, then regenerate.

## Principles

1. **This is not a Cytotec site.** Clusters A and B (misoprostol and
   abortion-related medical information) are capped at 14 of 100 topics, and are
   already largely covered by the existing corpus. The growth of the site is in
   women's health, pregnancy, PCOS, ectopic pregnancy, fertility and
   gynaecological emergencies.
2. **One intent per URL.** No pages that differ only by a keyword variation. If
   two topics resolve to the same searcher need, they are one article.
3. **No doorway city pages.** A city is named only where genuinely local
   information changes the reader's next step (service pathways, official
   bodies). Otherwise the article is country-level or region-neutral. See
   \`docs/geo-coverage.md\` and \`content/geo-coverage.json\`.
4. **No fabricated claims.** No invented doctors, statistics, affiliations,
   reviews or partnerships. Legal/regulatory statements require an official
   national source; where none can be verified, the article says so explicitly.
5. **Nothing in this plan sells or brokers medicine.** Every article routes the
   reader to licensed care, never to a seller.

## Status vocabulary

IDEA → RESEARCH → OUTLINE → DRAFT → REVIEW → READY → PUBLISHED → UPDATED.
\`PUBLISHED\`/\\\`UPDATED\\\` rows carry their live URL in Target URL.
Publishing is always human-reviewed — the map plans, the editor decides.

## Summary

| Dimension | Value |
|---|---|
| Topics | ${map.items.length} |
| By status | ${Object.entries(statusCount).map(([k, v]) => `${k} ${v}`).join(" · ")} |
| By priority | ${Object.entries(priorityCount).map(([k, v]) => `${k} ${v}`).join(" · ")} |
| P0 topics | ${p0 || "—"} |
| P0 complete | ${p0Done.length}/${p0Items.length} |

---

`;

let body = "";
for (const cluster of map.clusters) {
  const items = byCluster.get(cluster.id) ?? [];
  body += `## Cluster ${cluster.id} — ${cluster.title} (${items.length})\n\n`;
  body += `Pillar: \`${cluster.pillar}\` · Site cluster: \`${cluster.siteClusterId}\`\n\n`;
  body += `| ID | Topic | Primary keyword | Secondary keywords | Intent | Country | City relevance | Priority | Target URL | Parent | Related | Status |\n`;
  body += `|---|---|---|---|---|---|---|---|---|---|---|---|\n`;
  for (const item of items) body += `| ${row(item)} |\n`;
  body += "\n---\n\n";
}

const tail = `## Sequencing

**P0** topics carry the highest intent-to-effort ratio and establish the topical
spine the rest of the map links into. P1 (${p1}) fills out each cluster once its
P0 pillar is live. P2 (${p2}) adds depth and long-tail. P3 (${p3}) is gated on
verified official sourcing per country (topic C-014).

## What is deliberately excluded

- **City pages.** No Riyadh/Jeddah/Dubai/Manama landing pages. None of the
  target topics has city-level search intent with genuinely different
  information; building them would create doorway pages. The exceptions are
  country-level pages where the health system actually differs, citing that
  country's own official sources (see \`docs/geo-coverage.md\`).
- **Duplicate-intent variants** (merged into one topic).
- **Keyword-modifier pages** that repeat one query with a swapped adjective.

## Companion documents

- \`docs/url-inventory.md\` — live URLs + legacy URL handling
- \`content/redirects.json\` + \`vercel.json\` — 301/410 edge rules
- \`docs/competitor-research.md\` + \`content/competitors.json\` — gap matrix
- \`docs/geo-coverage.md\` + \`content/geo-coverage.json\` — Saudi/GCC decisions
- \`docs/backlink-strategy.md\` — digital PR architecture
- \`docs/seo-audit.md\` — full-site SEO audit output
`;

fs.writeFileSync(path.join(ROOT, "content-strategy-100.md"), head + body + tail);
console.log(`[strategy] wrote content-strategy-100.md (${map.items.length} topics, ${map.clusters.length} clusters)`);
